common_properties: &common_properties
  docker:
    - image: circleci/node:14.15.0-browsers
  working_directory: ~/les-cols-verts/les-cols-verts

version: 2
jobs:
  checkout_code:
    <<: *common_properties
    steps:
      - checkout
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - save_cache:
          key: v2-code-{{ checksum ".circle-cache-key" }}
          paths:
            - ~/les-cols-verts/les-cols-verts

  install_front:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v2-front-dependencies-{{ checksum "front/yarn.lock" }}
      - run:
          name: Install front
          command: yarn install:front --frozen-lockfile
      - save_cache:
          key: v2-front-dependencies-{{ checksum "front/yarn.lock" }}
          paths:
            - ./front/node_modules

  test_front:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v2-front-dependencies-{{ checksum "front/yarn.lock" }}
      - run:
          name: Lint front
          command: yarn lint:front
      - run:
          name: Test front
          command: yarn test:front:ci
      - store_test_results:
          path: /tmp/circleci-test-results/front

  build_front:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v2-front-dependencies-{{ checksum "front/yarn.lock" }}
      - run: yarn build:front
      - save_cache:
          key: v2-front-build-{{ checksum "front/yarn.lock" }}
          paths:
            - ./front/dist

  deploy_branch:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy branch to Heroku branch
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/les-cols-verts-branch.git $CIRCLE_BRANCH:master --force

  validate_html5v:
    <<: *common_properties
    steps:
      - run: yarn add html5-validator
      - run: ./node_modules/.bin/html5v https://french-test.les-cols-verts.me/
      - run: ./node_modules/.bin/html5v https://english-test.les-cols-verts.me/articles/85

  validate_html5v_branch:
    <<: *common_properties
    steps:
      - run: yarn add html5-validator
      - run: ./node_modules/.bin/html5v https://les-cols-verts-branch.herokuapp.com/
      - run: ./node_modules/.bin/html5v https://les-cols-verts-branch.herokuapp.com/articles/85

  lighthouse:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run: yarn lighthouse

  bundlesize:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - restore_cache:
          keys:
            - v2-front-build-{{ checksum "front/yarn.lock" }}
      - run: yarn bundlesize

  webpagetest:
    <<: *common_properties
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run: yarn add webpagetest
      - run: ./node_modules/.bin/webpagetest test https://french-test.les-cols-verts.me/ --first --poll --specs tools/webpagetest-threshold.json -k $WEBPAGETEST_API_KEY
      - run: ./node_modules/.bin/webpagetest test https://english-test.les-cols-verts.me/articles/85 --first --poll --specs tools/webpagetest-article-threshold.json -k $WEBPAGETEST_API_KEY

  deploy_staging:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy dev to Heroku staging
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/les-cols-verts-test.git dev:master

  deploy_master:
    <<: *common_properties
    shell: /bin/bash --login
    steps:
      - run: echo "${CIRCLE_BRANCH}_${CIRCLE_SHA1}" > .circle-cache-key
      - restore_cache:
          keys:
            - v2-code-{{ checksum ".circle-cache-key" }}
      - run:
          name: Deploy master to Recontact (Prod) - Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/les-cols-verts.git master

workflows:
  version: 2
  les-cols-verts-workflow:
    jobs:
      - checkout_code
      - install_front:
          requires:
            - checkout_code
      - test_front:
          requires:
            - install_front
      - build_front:
          requires:
            - install_front
      - deploy_branch:
          requires:
            - test_front
            - build_front
          filters:
            branches:
              ignore:
                - dev
                - master
      - validate_html5v_branch:
          requires:
            - deploy_branch
      - validate_html5v:
          requires:
            - deploy_staging
      - lighthouse:
          requires:
            - deploy_staging
      - webpagetest:
          requires:
            - deploy_staging
      - bundlesize:
          requires:
            - deploy_staging
      - deploy_staging:
          requires:
            - test_front
            - build_front
          filters:
            branches:
              only: dev
      - deploy_master:
          requires:
            - test_front
            - build_front
          filters:
            branches:
              only: master
