export const collectifs = [
  {
    // https://www.gps-longitude-latitude.net/
    location: { lng: 3.518332, lat: 50.357113 },
    center: 'Cols verts Valenciennes',
    url: 'http://www.lescolsverts.com/collectifs/valenciennes',
    address: '75 bis rue Jean Jaurès',
    city: ' 59410 Valenciennes',
    remark: 'Éventuelles remarques pouvant être ajoutées',
  },
  {
    location: { lng: -1.6586876, lat: 48.0894659 },
    center: 'Cols verts Rennes',
    description: 'Le potager des cultures',
    url: 'http://www.lescolsverts.com/collectifs/rennes',
    address: 'rue de Hongrie',
    city: '35200 Rennes',
    remark: 'Éventuelles remarques pouvant être ajoutées',
  },
  {
    location: { lng: 2.1700918, lat: 43.94202 },
    center: 'Cols verts Albi',
    description: 'Ferme du Gô, Urba Terra',
    url: 'http://www.lescolsverts.com/collectifs/albi',
    address: 'Chemin du Go',
    city: '81000 Albi',
    remark: 'Éventuelles remarques pouvant être ajoutées',
  },
  {
    location: { lng: 3.876716, lat: 43.610769 },
    center: 'Cols verts Montpellier',
    description: 'Bassin de Thau - quartier de Frontignan',
    url: 'http://www.lescolsverts.com/collectifs/montpellier',
    address: 'Bassin de Thau',
    city: '00000 Montpellier',
    remark: 'Éventuelles remarques pouvant être ajoutées',
  },
  {
    location: { lng: 7.752111, lat: 48.573405 },
    center: 'Cols verts Strasbourg',
    description: undefined,
    url: 'http://www.lescolsverts.com/collectifs/strasbourg',
    address: 'non communiquée',
    city: '00000 Strasbourg',
    remark: 'Éventuelles remarques pouvant être ajoutées',
  },
  {
    location: { lng: -61.024174, lat: 14.641528 },
    center: 'Ta Nou',
    description: undefined,
    url: 'http://www.lescolsverts.com/collectifs/martinique',
    address: 'en périphérie de la commune du Prêcheur',
    city: '00000 Le Prêcheur',
    remark: 'Éventuelles remarques pouvant être ajoutées',
  },
  {
    location: { lng: 11.045721, lat: 35.502446 },
    description: 'Cols verts Tunisie',
    center: 'Mahdia',
    url: 'http://www.lescolsverts.com/collectifs/mahdia',
    address: 'non communiquée',
    city: '00000 Mahdia',
    remark: 'Éventuelles remarques pouvant être ajoutées',
  },
];
