export const collectifs = [
  {
    // https://www.gps-longitude-latitude.net/
    location: { lng: 3.518332, lat: 50.357113 },
    description: 'Cols verts Valenciennes',
    url: 'http://www.lescolsverts.com/collectifs/valenciennes',
    address: '1, rue du paradis des cols verts',
    city: '00000 Valenciennes',
    remark: 'Ouvert le lundi de 18h à 20h',
  },
  {
    location: { lng: -1.677793, lat: 48.117266 },
    description: 'Cols verts Rennes',
    url: 'http://www.lescolsverts.com/collectifs/rennes',
    address: '1, rue du paradis des cols verts',
    city: '00000 Rennes',
    remark: 'Ouvert le lundi de 18h à 20h',
  },
  {
    location: { lng: 2.148641, lat: 43.925085 },
    description: 'Cols verts Albi',
    url: 'http://www.lescolsverts.com/collectifs/albi',
    address: '1, rue du paradis des cols verts',
    city: '00000 Albi',
    remark: 'Ouvert le lundi de 18h à 20h',
  },
  {
    location: { lng: 3.876716, lat: 43.610769 },
    description: 'Cols verts Montpellier',
    url: 'http://www.lescolsverts.com/collectifs/montpellier',
    address: '1, rue du paradis des cols verts',
    city: '00000 Montpellier',
    remark: 'Ouvert le lundi de 18h à 20h',
  },
  {
    location: { lng: 7.752111, lat: 48.573405 },
    description: 'Cols verts Strasbourg',
    url: 'http://www.lescolsverts.com/collectifs/strasbourg',
    address: '1, rue du paradis des cols verts',
    city: '00000 Strasbourg',
    remark: 'Ouvert le lundi de 18h à 20h',
  },
  {
    location: { lng: -61.024174, lat: 14.641528 },
    description: 'Cols verts Martinique',
    url: 'http://www.lescolsverts.com/collectifs/martinique',
    address: '1, rue du paradis des cols verts',
    city: '00000 Martinique',
    remark: 'Ouvert le lundi de 18h à 20h',
  },
  {
    location: { lng: 11.045721, lat: 35.502446 },
    description: 'Cols verts Mahdia',
    url: 'http://www.lescolsverts.com/collectifs/mahdia',
    address: '1, rue du paradis des cols verts',
    city: '00000 Mahdia',
    remark: 'Ouvert le lundi de 18h à 20h',
  },
];
